{{- if .Values.git.credentials.enabled }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: qtodo-git-credentials
  namespace: {{ .Release.Namespace | default .Values.global.namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: qtodo-git-credentials
    template:
      type: kubernetes.io/basic-auth
      metadata:
        annotations:
          tekton.dev/git-0: {{ .Values.git.credentials.host | quote }}
      data:
        username: {{ printf "{{ .%s }}" .Values.git.credentials.usernameKey | quote }}
        password: {{ printf "{{ .%s }}" .Values.git.credentials.passwordKey | quote }}
  data:
    - secretKey: {{ .Values.git.credentials.usernameKey }}
      remoteRef:
        key: {{ .Values.git.credentials.vaultPath }}
        property: {{ .Values.git.credentials.usernameKey }}
    - secretKey: {{ .Values.git.credentials.passwordKey }}
      remoteRef:
        key: {{ .Values.git.credentials.vaultPath }}
        property: {{ .Values.git.credentials.passwordKey }}
{{- end }}
